name: Markdown links verifier
on: pull_request

jobs:
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 #@v2

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@2afb5acdf77edc7d6c7fecbe3387aca169bd3eec #@v0.0.9.1
